var hierarchy =
[
    [ "AllocatedBuffer", "struct_allocated_buffer.html", null ],
    [ "AllocatedImage", "struct_allocated_image.html", null ],
    [ "CameraComponent", "struct_camera_component.html", null ],
    [ "ComponentListBase", "struct_component_list_base.html", [
      [ "ComponentListDerived< T >", "struct_component_list_derived.html", null ]
    ] ],
    [ "DescriptorAllocator", "struct_descriptor_allocator.html", null ],
    [ "DescriptorLayoutBuilder", "struct_descriptor_layout_builder.html", null ],
    [ "FrameData", "struct_frame_data.html", null ],
    [ "GamePadActionWrapper", "struct_game_pad_action_wrapper.html", null ],
    [ "GamepadStateWrapper", "struct_gamepad_state_wrapper.html", null ],
    [ "GeoSurface", "struct_geo_surface.html", null ],
    [ "GlobalSceneData", "struct_global_scene_data.html", null ],
    [ "GPUDrawPushConstants", "struct_g_p_u_draw_push_constants.html", null ],
    [ "GPUMeshBuffers", "struct_g_p_u_mesh_buffers.html", null ],
    [ "KeyProperties", "struct_key_properties.html", null ],
    [ "LavaAllocator", "class_lava_allocator.html", null ],
    [ "LavaBuffer", "class_lava_buffer.html", null ],
    [ "LavaDescriptorManager", "class_lava_descriptor_manager.html", null ],
    [ "LavaDevice", "class_lava_device.html", null ],
    [ "LavaDiffuseRenderSystem", "class_lava_diffuse_render_system.html", null ],
    [ "LavaECSManager", "class_lava_e_c_s_manager.html", null ],
    [ "LavaEngine", "class_lava_engine.html", null ],
    [ "LavaFrameData", "class_lava_frame_data.html", null ],
    [ "LavaImage", "class_lava_image.html", null ],
    [ "LavaInmediateCommunication", "class_lava_inmediate_communication.html", null ],
    [ "LavaInput", "class_lava_input.html", null ],
    [ "LavaInstance", "class_lava_instance.html", null ],
    [ "LavaJobSystem", "class_lava_job_system.html", null ],
    [ "LavaLuaScript", "class_lava_lua_script.html", null ],
    [ "LavaLuaSystem", "class_lava_lua_system.html", null ],
    [ "LavaMesh", "class_lava_mesh.html", null ],
    [ "LavaNormalRenderSystem", "class_lava_normal_render_system.html", null ],
    [ "LavaPBRMaterial", "class_lava_p_b_r_material.html", null ],
    [ "LavaPBRMaterialProperties", "struct_lava_p_b_r_material_properties.html", null ],
    [ "LavaPBRRenderSystem", "class_lava_p_b_r_render_system.html", null ],
    [ "LavaPipeline", "class_lava_pipeline.html", null ],
    [ "LavaSurface", "class_lava_surface.html", null ],
    [ "LavaSwapChain", "class_lava_swap_chain.html", null ],
    [ "LavaUpdateSystem", "class_lava_update_system.html", null ],
    [ "LavaWindow", "class_lava_window.html", null ],
    [ "LavaWindowSystem", "class_lava_window_system.html", null ],
    [ "LavaWorld", "class_lava_world.html", null ],
    [ "LightComponent", "struct_light_component.html", null ],
    [ "LightShaderStruct", "struct_light_shader_struct.html", null ],
    [ "LuaScriptComponent", "struct_lua_script_component.html", null ],
    [ "MaterialPBRProperties", "struct_material_p_b_r_properties.html", null ],
    [ "MeshAsset", "struct_mesh_asset.html", null ],
    [ "MeshProperties", "struct_mesh_properties.html", null ],
    [ "PipelineBuilder", "class_pipeline_builder.html", null ],
    [ "PipelineConfig", "struct_pipeline_config.html", null ],
    [ "DescriptorAllocator::PoolSizeRatio", "struct_descriptor_allocator_1_1_pool_size_ratio.html", null ],
    [ "LavaDescriptorManager::PoolSizeRatio", "struct_lava_descriptor_manager_1_1_pool_size_ratio.html", null ],
    [ "QueueFamilyIndices", "struct_queue_family_indices.html", null ],
    [ "RenderComponent", "struct_render_component.html", null ],
    [ "RotateComponent", "struct_rotate_component.html", null ],
    [ "SwapChainSupportDetails", "struct_swap_chain_support_details.html", null ],
    [ "TransformComponent", "struct_transform_component.html", null ],
    [ "UpdateComponent", "struct_update_component.html", null ],
    [ "Vertex", "struct_vertex.html", null ],
    [ "VertexWithTangents", "struct_vertex_with_tangents.html", null ]
];