name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "Cgroig"
        git config --global user.email "garciaroi@esat-alumni.com"

    - name: Install Doxygen
      run: |
        choco install doxygen.install

    - name: Add Doxygen to PATH (if necessary)
      run: |
        $doxygen_path = "C:\Program Files\doxygen\bin"  # Ruta donde debería estar instalado Doxygen
        if (-not (Test-Path "$doxygen_path\doxygen.exe")) {
          Write-Error "Doxygen no se ha instalado correctamente."
        } else {
          $env:Path += ";$doxygen_path"
          Write-Host "Doxygen está en el PATH."
        }

    - name: Verify Doxygen installation
      run: '"C:\Program Files\doxygen\bin\doxygen.exe" --version'  # Comando con comillas

    - name: Configure GitHub token for authentication
      run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: Run the .bat script
      run: .\updatedoc.bat

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Update documentation"
        git push

