name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "Cgroig"
        git config --global user.email "garciaroi@esat-alumni.com"

    - name: Install Doxygen
      run: |
        choco install doxygen --version 1.9.6  # Usa Chocolatey para instalar Doxygen


    - name: Configure GitHub token for authentication
      run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: Run the .bat script
      run: .\updatedoc.bat

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Update documentation"
        git push

